config/routes.rb
Rails.application.routes.draw do
  concern :statusable do
    resources :order_statuses, shallow: true
  end
  resources :line_items, only: [:create, :update, :destroy]
  resources :carts
  resources :instruments
  resources :categories, only: [:show, :index]
  resources :orders, concerns: :statusable
  resources :order_instruents, only: [], concerns: :statusable
  namespace :store do
    get :sales
    get '/sales/:id', action: :sale, as: :sale
    get :instruments
    get :orders, to: '/orders#index'
  end
  devise_for :users, controllers: {
      registrations: 'registrations',
      sessions: 'sessions'
  }
  root 'instruments#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar is-warning" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <h1 class="title is-5">Music World</h1>
    <% end %>
  </div>

  <div id="navbar" class="navbar-menu">
    <div class="navbar-item has-dropdown is-hoverable">
      <a class="navbar-link">
        Instrument category
      </a>
      <div class="navbar-dropdown">
        <%= build_menu %>
        <a class="navbar-item">
          Jobs
        </a>
        <a class="navbar-item">
          Contact
        </a>
      </div>
    </div>
  </div>

  <div class="navbar-end">
    <div class="navbar-item">
      <div class="field is-grouped">

        <% if total_cart_items %>
          <%= link_to cart_path(@cart), class: "navbar-item button is-warning" do %>
              <span class="icon is-small">
                <i class="fa fa-shopping-cart"></i>
              </span>
            <span>Cart
              <%= cart_count_over_one %>
                </span>
          <% end %>
        <% end %>

        <% if user_signed_in? %>
          <%= link_to 'Sell', new_instrument_path, class: "navbar-item button is-dark" %>

          <div class="navbar-item has-dropdown is-hoverable">
            <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
            <div class="navbar-dropdown is-right">
              <%= link_to current_user.name, edit_user_registration_path, class: "navbar-item" %>
              <%= link_to 'Your store', orders_path, class: "navbar-item" %>
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-item" %>
            </div>
          </div>
        <% else %>

          <%= link_to "Sign In", new_user_session_path, class: "navbar-item button is-warning" %>
          <%= link_to "Sign up", new_user_registration_path, class: "navbar-item button is-warning" %>

        <% end %>

      </div>
    </div>
  </div>
  </div>
</nav>

app/views/layouts/shared/_user_panel.html.erb
<div class="columns">
  <div class="column is-2">
    <aside class="menu">
      <p class="menu-label">
        Your Store
      </p>
      <ul class="menu-list">
        <% %>
        <li><%= link_to 'Your orders', store_orders_path %></li>
        <li><%= link_to 'Your sales', store_sales_path %></li>
        <li><%= link_to 'Your instruments', store_instruments_path %></li>
      </ul>

    </aside>
  </div>
  <div class="column is-10">
    <%= yield %>
  </div>
</div>