config/routes.rb
Rails.application.routes.draw do
  concern :statusable do
    resources :order_statuses, shallow: true
  end
  resources :line_items, only: [:create, :update, :destroy]
  resources :carts
  resources :instruments
  resources :categories, only: [:show, :index]
  resources :orders, concerns: :statusable
  resources :order_instruents, only: [], concerns: :statusable
  namespace :store do
    get :sales
    get '/sales/:id', action: :sale, as: :sale
    get :instruments
    get :orders, to: '/orders#index'
  end
  devise_for :users, controllers: {
      registrations: 'registrations',
      sessions: 'sessions'
  }
  root 'instruments#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  belongs_to :user, optional: true

  def add_instrument(instrument, quantity = 1)
    current_item = line_items.find_by(instrument_id: instrument.id)
    if current_item
      current_item.quantity += quantity
    else
      current_item = line_items.build(instrument_id: instrument.id, quantity: quantity)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end

  def instruments_quantity
    line_items.sum(&:quantity)
  end

  def clear_items
    line_items.destroy_all
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  authorize_resource

  def index
    @carts = Cart.all
  end

  def show
  end

  def new
    @cart = Cart.new
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html {redirect_to @cart, notice: 'Cart was successfully created.'}
        format.json {render :show, status: :created, location: @cart}
      else
        format.html {render :new}
        format.json {render json: @cart.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html {redirect_to @cart, notice: 'Cart was successfully updated.'}
        format.json {render :show, status: :ok, location: @cart}
      else
        format.html {render :edit}
        format.json {render json: @cart.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html {redirect_to root_path, notice: 'Cart was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  def cart_params
    params.fetch(:cart, {})
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: "That cart doesn't exist"
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="keep-shopping pv1 mt4 has-text-right">
  <%= link_to 'Keep Shopping', instruments_path, class: 'button is-warning' %>
</div>
<hr/>
<section class="section">
  <%= render(@cart.line_items) %>

  <div class="columns">
    <div class="column">
      <%= button_to 'Empty Cart', @cart, method: :delete, data: {confirm: "Are you sure? "}, class: "button is-danger" %>
    </div>
    <div class="column total has-text-right">
      <h4 class="title is-4">
        <span class="f5 has-text-grey">Total:</span> <%= number_to_currency(@cart.total_price) %>
      </h4>
      <%= link_to 'Make order', new_order_path, class: 'button is-primary' %>
    </div>
  </div>
</section>