config/routes.rb
Rails.application.routes.draw do
  concern :statusable do
    resources :order_statuses, shallow: true
  end
  resources :line_items, only: [:create, :update, :destroy]
  resources :carts
  resources :instruments
  resources :categories, only: [:show, :index]
  resources :orders, concerns: :statusable
  resources :order_instruents, only: [], concerns: :statusable
  namespace :store do
    get :sales
    get '/sales/:id', action: :sale, as: :sale
    get :instruments
    get :orders, to: '/orders#index'
  end
  devise_for :users, controllers: {
      registrations: 'registrations',
      sessions: 'sessions'
  }
  root 'instruments#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  before_destroy :not_refereced_by_any_line_item
  belongs_to :user, optional: true
  belongs_to :category
  has_many :line_items
  has_many :orders_instruments

  mount_uploader :image, ImageUploader
  serialize :image, JSON # If you use SQLite, add this line
  scope :not_sold, -> {where.not(instruments: {quantity: 0})}
  validates :title, :brand, :price, :model, presence: true
  validates :description, length: {maximum: 1000, too_long: "%{count} characters is the maximum aloud. "}
  validates :title, length: {maximum: 140, too_long: "%{count} characters is the maximum aloud. "}
  validates :price, length: {maximum: 7}

  BRAND = %w{ Fender Gibson Epiphone ESP Martin Dean Taylor Jackson PRS  Ibanez Charvel Washburn }.freeze
  FINISH = %w{ Black White Navy Blue Red Clear Satin Yellow Seafoam }.freeze
  CONDITION = %w{ New Excellent Mint Used Fair Poor }.freeze

  private

  def not_refereced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end

end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:index, :show]


  def index
    # @instruments = Instrument.not_sold.includes(:user).order("created_at desc")
    @pagy, @instruments = pagy(Instrument.not_sold.includes(:user).order("created_at desc"), items: 10)
  end


  def show
  end

  def new
    @instrument = current_user.instruments.build
  end

  def edit
  end

  def create
    @instrument = current_user.instruments.build(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html {redirect_to @instrument, notice: 'Instrument was successfully created.'}
        format.json {render :show, status: :created, location: @instrument}
      else
        format.html {render :new}
        format.json {render json: @instrument.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html {redirect_to @instrument, notice: 'Instrument was successfully updated.'}
        format.json {render :show, status: :ok, location: @instrument}
      else
        format.html {render :edit}
        format.json {render json: @instrument.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @instrument.destroy
    respond_to do |format|
      format.html {redirect_to instruments_url, notice: 'Instrument was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  def instrument_params
    params.require(:instrument).permit(:brand, :model, :description, :condition, :finish, :title, :price, :image, :category_id)
  end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper

  def instrument_author(instrument)
    user_signed_in? && current_user.id == instrument.user_id
  end

end

app/views/instruments/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @instrument, html: {multipart: true} do |f| %>
      <%= f.error_notification %>

      <div class="columns">

        <div class="field column is-9">
          <div class="control">
            <%= f.input :title, required: true, input_html: {class: "input"}, wrapper: false, label_html: {class: "label"} %>
          </div>
        </div>

        <div class="field column">
          <div class="control">
            <%= f.input :price, required: true, input_html: {class: "input", maxlength: 7}, wrapper: false, label_html: {class: "label"} %>
          </div>
        </div>

      </div>

      <div class="columns">
        <div class="column is-9">
          <div class="field">
            <div class="control">
              <%= f.input :model, required: true, input_html: {class: "input"}, wrapper: false, label_html: {class: "label"} %>
            </div>
          </div>
        </div>
        <div class="column">
          <div class="field">
            <label class="label">Subject</label>
            <div class="control">
              <div class="select">
                <%= f.input :category_id, collection: Category.all, promt: 'Select category', label: false, wrapper: false %>

              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.input :description, required: true, input_html: {class: "textarea"}, wrapper: false, label_html: {class: "label"} %>
        </div>
      </div>

      <div class="columns">
        <div class="field column is-4">
          <div class="control">
            <label class="label">Brand</label>
            <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :brand, collection: Instrument::BRAND, prompt: "Select brand" %>
                </span>
              <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
            </div>
          </div>
        </div>

        <div class="field column is-4">
          <div class="control">
            <label class="label">Finish</label>
            <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :finish, collection: Instrument::FINISH, prompt: "Select finish" %>
                </span>
              <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
            </div>
          </div>
        </div>

        <div class="field column is-4">
          <div class="control">
            <label class="label">Condition</label>
            <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :condition, collection: Instrument::CONDITION, prompt: "Select condition" %>
                </span>
              <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
            </div>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <label class="label">Add images</label>
          <div class="file">
            <label class="file-label">
              <%= f.input :image, as: :file, input_html: {class: "file-input instrument-image"}, label: false, wrapper: false %>
              <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Choose a file…</span>
                  </span>
            </label>
          </div>
        </div>
      </div>
      <output id="list"></output>
      <hr/>

      <div class="field is-grouped">
        <div class="control">
          <%= f.button :submit, class: 'button is-warning' %>
          <%= link_to 'Cancel', instruments_path, class: 'button is-light' %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/instruments/_instrument.html.erb
<div class="instrument border-light">
  <div class="instrument-thumb">
    <%= link_to image_tag(instrument.image_url(:thumb)), instrument %>

    <% if instrument.condition? %>
      <div class="condition">
        <span class="tag is-dark"><%= instrument.condition %></span>
      </div>
    <% end %>
  </div>


  <div class="pa3">

    <h3 class="fw7 f4 title"><%= link_to instrument.title, instrument %></h3>

    <p class="has-text-gray fg pt1">Sold by <%= instrument.user.name %></p>

    <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(instrument.price) %></p>

    <% if instrument_author(instrument) %>
      <%= link_to 'Edit', edit_instrument_path(instrument), class: "button is-small" %>
      <%= link_to 'Delete', instrument, method: :delete, data: {confirm: "Are you sure ?"}, class: "button is-small" %>
    <% end %>

  </div>
</div>

app/views/instruments/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing Instrument
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', instrument: @instrument %>
</div>

app/views/instruments/index.html.erb
<% content_for :header do %>
  <section class="hero">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Browse the latest instruments on Flanger
        </h1>
      </div>
    </div>
  </section>
<% end %>



<div class="instrument-index-grid pt4">
  <%= render @instruments %>
</div>
<br/>
<%== pagy_bulma_nav(@pagy) %>

app/views/instruments/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Sell an Instrument
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', instrument: @instrument %>
</div>

app/views/instruments/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @instrument.title %></h1>

      <ul class="pv1">
        <% if @instrument.brand? %>
          <li class="inline-block pr3"><%= @instrument.brand %></li>
        <% end %>

        <li class="inline-block pr3"><%= @instrument.model %></li>

        <% if @instrument.condition? %>
          <li class="inline-block pr3"><%= @instrument.condition %></li>
        <% end %>
      </ul>

      <div class="feature-image">
        <%= image_tag(@instrument.image_url(:default)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

        <h3 class="subtitle is-4">Description</h3>
        <%= @instrument.description %>


        <h3 class="subtitle is-4 pt5">Product Specs</h3>

        <table class="table is-narrow">
          <tr>
            <td class="has-text-weight-bold">Category:</td>
            <td><%= @instrument.category.name %></td>
          </tr>
          <% if @instrument.condition %>
            <tr>
              <td class="has-text-weight-bold">Condition:</td>
              <td><%= @instrument.condition %></td>
            </tr>
          <% end %>

          <% if @instrument.finish %>
            <tr>
              <td class="has-text-weight-bold">Finish:</td>
              <td><%= @instrument.finish %></td>
            </tr>
          <% end %>

          <% if @instrument.brand %>
            <tr>
              <td class="has-text-weight-bold">Brand:</td>
              <td><%= @instrument.brand %></td>
            </tr>
          <% end %>

          <tr>
            <td class="has-text-weight-bold">Model:</td>
            <td><%= @instrument.model %></td>
          </tr>
        </table>
      </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@instrument.price) %></h4>
        <p class="has-text-centered mb4">Sold by <%= @instrument.user.name %></p>
        <%= button_to 'Add to cart', line_items_path(instrument_id: @instrument), class: 'button is-warning add-to-cart' if @instrument.user != current_user %>
      </div>
    </div>
  </div>

  <% if instrument_author(@instrument) %>
    <%= link_to 'Edit', edit_instrument_path(@instrument), class: 'button' %>
    <%= link_to 'Destroy', @instrument, method: :delete, data: {confirm: 'Are you sure?'}, class: 'button' %>
  <% end %>
</section>