config/routes.rb
Rails.application.routes.draw do
  concern :statusable do
    resources :order_statuses, shallow: true
  end
  resources :line_items, only: [:create, :update, :destroy]
  resources :carts
  resources :instruments
  resources :categories, only: [:show, :index]
  resources :orders, concerns: :statusable
  resources :order_instruents, only: [], concerns: :statusable
  namespace :store do
    get :sales
    get '/sales/:id', action: :sale, as: :sale
    get :instruments
    get :orders, to: '/orders#index'
  end
  devise_for :users, controllers: {
      registrations: 'registrations',
      sessions: 'sessions'
  }
  root 'instruments#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  before_action :authenticate_user!
  before_action :find_order, only: [:sale]

  def sales
    authorize! :sales, :store
    @orders = Order.includes(orders_instruments: {instrument: :user}).preload(:order_statuses)
                  .where(users: {id: current_user.id})
                  .order(created_at: :desc)
    @orders = @orders.by_status(params[:status]) if params.key?(:status)
    @pagy, @orders = pagy_countless(@orders.decorate, items: 20)

  end

  def sale
    authorize! :sale, :store, @order
    @order = @order.decorate
  end

  def instruments
    authorize! :instruments, :store
    @pagy, @instruments = pagy_countless(current_user.instruments, items: 20)

  end


  private
  def find_order
    @order = Order.includes(orders_instruments: {instrument: :user}).find(params[:id])
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/instruments.html.erb
<% content_for :header do %>
  <section class="hero">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Browse your instruments
        </h1>
      </div>
    </div>
  </section>
<% end %>

<%= render layout: 'layouts/shared/user_panel' do %>

  <div class="instrument-index-grid pt4">
    <%= render @instruments %>
  </div>
  <br/>
  <%== pagy_bulma_nav(@pagy) %>

<% end %>

app/views/store/sale.html.erb
<% content_for :header do %>
  <section class="hero">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Sale
        </h1>
      </div>
    </div>
  </section>
<% end %>
<%= render layout: 'layouts/shared/user_panel' do %>
  <div class="columns">
    <div class="column is-5">
      <div class="card orders-detail-cards">
        <header class="card-header">
          <p class="card-header-title">
            Order status
          </p>
        </header>
        <div class="card-content">
          <div class="content">
            <table class="table is-narrow is-half">
              <tr>
                <th class="has-text-weight-bold">Order status:</th>
                <th> <%= @order.status %></th>
              </tr>
              <tr>
                <th class="has-text-weight-bold">Payment status:</th>
                <th></th>
              </tr>
              <tr>
                <th class="has-text-weight-bold">Date of the order:</th>
                <th> <%= @order.created_at_local %></th>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="column">
      <div class="card orders-detail-cards">
        <header class="card-header">
          <p class="card-header-title">
            Payment
          </p>
        </header>
        <div class="card-content pt1">
          <div class="content">
            <table class="table is-borderless">
              <tr>
                <td>Instruments</td>
                <td><%= @order.total_price %>$</td>
              </tr>
              <tr>
                <td>Delivery</td>
                <td><%= @order.delivery_option.price %>$</td>
              </tr>
              <tr>
                <td><p>Total </p></td>
                <td><%= @order.total_amount %>$</td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card">
    <header class="card-header">
      <p class="card-header-title">
        Order status history
      </p>
    </header>
    <div class="card-content">
      <div class="content">
        <div class="table-container">
          <table class="table is-fullwidth">
            <thead>
            <tr>
              <td> Status</td>
              <td> Date reported</td>
            </tr>
            </thead>
            <tbody>
            <% @order.order_statuses.each do |status| %>
              <tr>
                <td><%= status.status_name %></td>
                <td><%= status.date_reported_local %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <br/>
  <div class="card">
    <header class="card-header">
      <p class="card-header-title">
        Ordered instruments
      </p>
    </header>
    <div class="card-content">
      <div class="content">
        <div class="table-container">
          <table class="table is-fullwidth">
            <tbody>
            <% @order.orders_instruments.each_with_index do |item, index| %>
              <tr id="row_order_status_<%= item.order_status.id %>">
                <td><%= index + 1 %></td>
                <td> <%= item.mini_thumb %></td>
                <td> <%= item.instrument_truncated_title %></td>
                <td> Quantity: <%= item.quantity %></td>
                <td> Price : <%= item.instrument.price %></td>
                <td> Status : <span class="order_status_preview"><%= item.order_status.status_name %></span></td>
                <td>
                  <%= simple_form_for(item.order_status, remote: true) do |f| %>
                    <div class="field">
                      <div class="control">
                        <div class="select">
                          <%= f.input :status, collection: OrderStatus.orders_instrument_statuses.map {|s| [OrderStatus.get_status(s[1]), s[1]]}, wrapper: false, label: false, selected: f.object.status_integer %>
                          <%= f.button :submit, data: {confirm: 'Are you sure? '} %>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <br/>
  <div class="card">
    <header class="card-header">
      <p class="card-header-title">
        Order details
      </p>
    </header>
    <div class="card-content">
      <div class="content">
        <div class="columns">
          <div class="column is-6">
            <h1 class="title is-6">Client Address</h1>
            <%= address_details @order %>
          </div>
          <div class="column is-6">
            <h1 class="title is-6">Delivery method</h1>
            <p><%= @order.delivery_method %></p>
            <p><%= @order.delivery_option.details %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/store/sales.html.erb
<% content_for :header do %>
  <section class="hero">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Your Orders
        </h1>
      </div>
    </div>
  </section>
<% end %>
<%= render layout: 'layouts/shared/user_panel' do %>
  <div class="level">
    <div class="level-left">
    </div>
    <div class="level-right">
      <p class="has-text-weight-semibold">Filter by status: </p>
      <div class="dropdown is-right pl3">
        <div class="dropdown-trigger">
          <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
            <span> Filters</span>
            <span class="icon is-small">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
          </button>
        </div>
        <div class="dropdown-menu" id="dropdown-menu" role="menu">
          <div class="dropdown-content">
            <%= link_to 'All', orders_path, class: 'dropdown-item' %>
            <% OrderStatus.statuses.each do |status| %>
              <%= link_to OrderStatus::STATUS_NAMES[status[0].to_sym], store_sales_path(status: status[0]), class: 'dropdown-item' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="table-container">
    <table class="table is-fullwidth is-striped">
      <thead>
      <tr>
        <td>Nr</td>
        <td>Instruments</td>
        <td>Order date</td>
        <td>Total price</td>
        <td>Quantity</td>
        <td>Status</td>
      </tr>
      </thead>
      <tbody>
      <% @orders.each_with_index do |order, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td>
            <%= link_to store_sale_path(order) do %>
              <ol type="1">
                <% order.orders_instruments.each do |order_instrument| %>
                  <li><%= order_instrument.instrument.title.truncate(70) %></li>
                <% end %>
              </ol>
            <% end %>

          </td>
          <td><%= order.created_at_local %></td>
          <td><%= order.total_amount %></td>
          <td><%= order.user_owned_instruments_quantity(current_user) %></td>
          <td><%= order.status %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <%== pagy_bulma_nav(@pagy) %>

<% end %>